image: node:16  # Use the Node.js version that fits your project

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm install

lint:
  stage: test
  script:
    - npm run lint
  dependencies:
    - install

test:
  stage: test
  script:
    - npm run test
  dependencies:
    - install

build:
  stage: build
  script:
    - npm run build
    - npm run build:types
  artifacts:
    paths:
      - dist/
